# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
arr2 = np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [7]:
arr3 = np.arange(10,49)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [8]:
arr3.shape

(39,)

5. Print the type of the previous array in question 3

In [10]:
print(arr3.dtype)

int32


6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\Users\\DELL\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


7. Print the dimension of the array in question 3


In [12]:
print(arr3.ndim)

1


8. Create a boolean array with all the True values

In [16]:
arr8 = np.arange(7)
boolean_arr = arr8 < 10
boolean_arr

array([ True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [22]:
arr9 = np.array([[np.arange(1,4)],
               [np.arange(4,7)]])
arr9

array([[[1, 2, 3]],

       [[4, 5, 6]]])

10. Create a three dimensional array



In [23]:
arr10 = np.array([[np.arange(1,4)],
               [np.ones(3)],
                 [np.zeros(3)]])
arr10

array([[[1., 2., 3.]],

       [[1., 1., 1.]],

       [[0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [40]:
arr11 = arr3[::-1]
arr11

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [42]:
arr12 = np.zeros(10)
arr12[4] = 1
arr12

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [43]:
arr13 = np.eye(3)
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [47]:
arr = np.array([1,2,3,4,5])
arr14 = np.array(arr, dtype=float)
arr14

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [51]:
arr1 = np.array([[1.,2.,3.],
                 [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                 [7.,2.,12.]])
arr15 = arr1 * arr2
arr15

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [53]:
arr1 = np.array([[1.,2.,3.],
                 [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                 [7.,2.,12.]])
arr16 = arr1 >= arr2
arr16

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [58]:
arr17 = np.arange(10)
arr17[np.arange(10) % 2 != 0]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [61]:
arr18 = arr17[np.arange(10) % 2 != 0] = -1
arr17

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [63]:
arr = np.arange(10)
arr19 = arr[4:8] = 12
arr19, arr

(12, array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9]))

20. Create a 2d array with 1 on the border and 0 inside

In [67]:
arr20 = np.eye(2,2)
arr20

array([[1., 0.],
       [0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [69]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[1:2,1:2] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [74]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [76]:
arr23 = np.arange(10).reshape(2,5)
arr23[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [79]:
arr24 = np.arange(10).reshape(2,5)
arr24[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [82]:
arr25 = np.arange(10).reshape(2,5)
arr25[:,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
arr26 = np.array(np.random.rand(10,10) * 10, dtype = 'int32')
print(arr26)
print('Min value in array is:',arr26.min())
print('Max value in array is:',arr26.max())

[[1 3 5 2 0 0 9 9 5 0]
 [1 8 9 0 6 3 5 3 8 5]
 [6 8 6 0 6 0 4 4 2 4]
 [8 0 2 8 3 2 5 0 4 1]
 [7 5 5 2 4 3 0 0 0 9]
 [7 6 4 2 2 5 1 2 1 7]
 [7 0 5 6 8 8 8 9 4 8]
 [9 5 4 9 6 9 8 8 0 4]
 [4 9 1 4 8 0 1 3 4 5]
 [1 4 5 7 8 8 2 1 1 5]]
Min value in array is: 0
Max value in array is: 9


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [56]:
a,b = np.array([1,2,3,2,3,4,3,4,5,6]), np.array([7,2,10,2,7,4,9,4,9,8])
arr18 = a == b
print('Common items between a and b is:',a[arr18])

Common items between a and b is: [2 2 4 4]


(array([1, 3], dtype=int64),)

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [59]:
print('Positions where elements of a and b match is:',np.where(a == b))

Positions where elements of a and b match is: (array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [101]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
print('Names is:\n',names)
print('\nData is:\n',data)
print('\nValues from data where name is not equal to Will:\n\n',data[names != 'Will'])

Names is:
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data is:
 [[-2.72364459 -0.4013882  -0.40580461  0.55255612]
 [-0.13083648 -1.59988755 -1.06302336 -0.53750402]
 [ 0.01310159  0.10654948 -0.66644536  0.21944481]
 [-0.42053713  0.17464273  0.32485598 -0.05897128]
 [ 0.2835362   2.53236338 -0.62575614 -0.54736885]
 [ 0.28560275  0.34163054 -1.42818883 -0.4842461 ]
 [-0.54200045  0.66289293 -1.29661141 -0.31002955]]

Values from data where name is not equal to Will:

 [[-2.72364459 -0.4013882  -0.40580461  0.55255612]
 [-0.13083648 -1.59988755 -1.06302336 -0.53750402]
 [-0.42053713  0.17464273  0.32485598 -0.05897128]
 [ 0.28560275  0.34163054 -1.42818883 -0.4842461 ]
 [-0.54200045  0.66289293 -1.29661141 -0.31002955]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [103]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
print('Names is:\n',names)
print('\nData is:\n',data)
print('\nValues from data where name are not equal to Will and Joe:\n\n',data[(names != 'Will') & (names !='Joe')])

Names is:
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data is:
 [[-0.71026184 -0.82447511 -0.31364843 -1.55549161]
 [-0.49450587 -1.40883017 -1.2793585  -0.26271133]
 [-0.42773632 -1.23094741 -0.81199427 -0.26805313]
 [ 0.34657886  0.20106205  0.59239731 -1.94321405]
 [ 0.12420281  1.03471915 -0.04797385 -0.07696505]
 [-0.32062491 -1.51017838  1.20555954  0.88555731]
 [-0.83500237 -0.02595622 -1.65654398  0.80588773]]

Values from data where name are not equal to Will and Joe:

 [[-0.71026184 -0.82447511 -0.31364843 -1.55549161]
 [ 0.34657886  0.20106205  0.59239731 -1.94321405]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [107]:
arr31 = np.arange(1,16).reshape(5,3)
arr31

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [110]:
arr32 = np.arange(1,17).reshape(2,2,4)
arr32

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [146]:
arr33 = arr32[::-1]
arr33

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [172]:
arr34 = np.random.rand(10)
print('Array values:\n\n',arr34)
arr34[arr34 < 0.5] = 0
print('\nArray with zero values if less than 0.5:\n\n',arr34)
print('\nAfter square root:\n\n',np.sqrt(arr34))

Array values:

 [0.84885179 0.38957944 0.48903003 0.01189997 0.61522225 0.76617868
 0.31704618 0.90421076 0.94322355 0.56488212]

Array with zero values if less than 0.5:

 [0.84885179 0.         0.         0.         0.61522225 0.76617868
 0.         0.90421076 0.94322355 0.56488212]

After square root:

 [0.92133153 0.         0.         0.         0.78436105 0.87531633
 0.         0.95089997 0.97119697 0.7515864 ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [49]:
arr35a = np.array(np.random.rand(12)*10, dtype = 'int32')
arr35b = np.array(np.random.rand(12)*10, dtype = 'int32')
print('1st array:',arr35a)
print('2nd array:',arr35b)

print(f'''\nmax values in 1st array as compare to 2nd: {arr35a[arr35a > arr35b]}
and position of these values are: {np.where(arr35a > arr35b)}''')

print(f'''\nmax values in 2nd array as compare to 1st:{arr35b[arr35a < arr35b]}
and position of these values are: {np.where(arr35a < arr35b)}''')

1st array: [1 3 3 2 9 0 8 1 9 4 8 9]
2nd array: [3 2 8 7 7 4 3 1 7 5 9 5]

max values in 1st array as compare to 2nd: [3 9 8 9 9]
and position of these values are: (array([ 1,  4,  6,  8, 11], dtype=int64),)

max values in 2nd array as compare to 1st:[3 8 7 4 5 9]
and position of these values are: (array([ 0,  2,  3,  5,  9, 10], dtype=int64),)


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [52]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [92]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print('1st Array:\n',a)
print('\n2nd Array:\n',b)
a = np.setdiff1d(a,b)
print('\nRemove items from 1st Array which is present in 2nd:\n',a)

1st Array:
 [1 2 3 4 5]

2nd Array:
 [5 6 7 8 9]

Remove items from 1st Array which is present in 2nd:
 [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [89]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
print('Array we have:\n',sampleArray)
print('\nNew column inserted:\n',newColumn.T)
sampleArray[:,1:2] = newColumn.T
print('\nAfter replacement column two, new array:\n',sampleArray)

Array we have:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

New column inserted:
 [[10]
 [10]
 [10]]

After replacement column two, new array:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [94]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print('1st Array:\n',x)
print('\n2nd Array:\n',y)
print('\nAfter dot product:\n',x.dot(y))

1st Array:
 [[1. 2. 3.]
 [4. 5. 6.]]

2nd Array:
 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

After dot product:
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [100]:
arr40 = np.random.rand(20)
print('Given Array:\n\n',arr40)
print('\nCumulative Sum of above array:\n\n',arr40.cumsum())

Given Array:

 [0.38555355 0.5502898  0.82220769 0.29011856 0.12812886 0.16083893
 0.49337724 0.19812914 0.27611511 0.19471433 0.31844632 0.50690549
 0.39444575 0.56800186 0.05223443 0.32614475 0.44882912 0.13186831
 0.55927726 0.01748011]

Cumulative Sum of above array:

 [0.38555355 0.93584335 1.75805104 2.0481696  2.17629846 2.33713739
 2.83051462 3.02864376 3.30475887 3.49947321 3.81791953 4.32482501
 4.71927076 5.28727262 5.33950704 5.66565179 6.11448091 6.24634922
 6.80562648 6.82310659]
