# Numpy_Assignment_2::

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
arr1 = np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [14]:
arr2 = np.vstack((arr1,np.full(10,1).reshape(2,5)))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [13]:
arr3 = np.hstack((arr1,np.full(10,1).reshape(2,5)))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
arr4 = arr1.reshape(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [18]:
arr5 = np.arange(15)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [19]:
arr6 = arr5.reshape(5,3)
arr6

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [27]:
arr7 = np.arange(25).reshape(5,5)
print('Array:\n',arr7)
arr7 *= arr7
print('\nSquare of Array:\n',arr7)

Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Square of Array:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [31]:
arr8 = np.arange(30).reshape(5,6)
print('Array:\n',arr8)
arrr8 = np.mean(arr8)
print('\nMean of Array:\n',arrr8)

Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Mean of Array:
 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [34]:
arr9 = arr8.std()
print('Standard deviation:',arr9)

Standard deviation: 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [38]:
arr10 = np.median(arr8)
print('Median:',arr10)

Median: 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [39]:
arr11 = arr8.T
print('Transpose of array:\n',arr11)

Transpose of array:
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [45]:
arr12 = np.arange(16).reshape(4,4)
print('Array:\n',arr12)
print('\nSum of Diagonal:',np.sum(np.diag(arr12)))

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum of Diagonal: 30


## Question:13

### Find the determinant of the previous array in Q12?

In [50]:
print('Determinant:',np.linalg.det(arr12))

Determinant: -2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [55]:
print('Array:\n',arr12)
print('5th percentile of an array:',np.percentile(arr12,5))
print('95th percentile of an array:',np.percentile(arr12,95))

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
5th percentile of an array: 0.75
95th percentile of an array: 14.25


## Question:15

### How to find if a given array has any null values?

In [58]:
arr15 = np.array([0,1,2,3,4,0,5,9,4,6])
print('Array has zero values at index no:',np.where(arr15 == 0))

Array has zero values at index no: (array([0, 5], dtype=int64),)
